###############################################################################
# AZURE AI LANDING ZONE - ROOT ORCHESTRATION
#
# Reference: https://github.com/Azure/AI-Landing-Zones
#
# This file composes all modules matching the AI Landing Zone reference
# architecture. The full topology deployed here mirrors the screenshot:
#
#   AI Foundry Agent Service standard setup
#   ├── AI Foundry Agent Service dependencies
#   │   ├── Storage Account (foundry artifacts)
#   │   ├── AI Search       (vector RAG index)
#   │   ├── Cosmos DB       (agent memory / session state)
#   │   └── Key Vault       (secrets and model keys)
#   └── Azure AI Foundry Service
#       └── AI Foundry Project
#           ├── AI Services endpoints  (Cognitive Services)
#           ├── Foundry models         (OpenAI deployments)
#           ├── Connections            (to Search, Storage, Cosmos)
#           └── Foundry Agent Service  (in ai-foundry-agent subnet)
#
#   AI Services Virtual Network (region 1 spoke)
#   ├── Jumpbox subnet              (admin VM)
#   ├── Private Endpoints subnet    (all service PEs)
#   ├── API Management subnet       (APIM internal VNet)
#   ├── AI Foundry Agent subnet     (agent runtime)
#   ├── Application Gateway subnet  (WAF ingress)
#   ├── Container App Env subnet    (GenAI microservices)
#   └── Build agent subnet          (CI/CD self-hosted agent)
#
#   GenAI app dependencies
#   ├── Cosmos DB, Key Vault, Storage Account, Container Registry, App Config
#
#   GenAI app microservices (Container App Environment)
#   ├── Frontend, Orchestrator, SK, MCP, Ingestion  (Dapr-enabled)
#
#   Enterprise and public knowledge sources
#   ├── Grounding with Bing
#   └── AI Search Service
#
#   Security & governance
#   ├── Subscription policy assignments
#   ├── Defender for Cloud
#   ├── Entra ID
#   └── Purview
#
# Toggle individual modules on/off via the deploy_* variables in tfvars.
###############################################################################

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.100"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.47"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }

  backend "azurerm" {}   # Configured via backend.hcl (generated by scripts/bootstrap.sh)
}

# -----------------------------------------------------------------------------
# PROVIDERS
# Spoke provider for landing zone resources.
# Hub provider alias available for DNS zone data sources if needed.
# Hub VNET peering is managed separately via scripts\setup-peering.ps1.
# -----------------------------------------------------------------------------
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy    = false
      recover_soft_deleted_key_vaults = true
    }
    resource_group {
      prevent_deletion_if_contains_resources = true
    }
  }
  subscription_id = var.spoke_subscription_id
  use_oidc        = true
}

provider "azurerm" {
  alias = "hub"
  features {}
  subscription_id = var.hub_subscription_id
  use_oidc        = true
}

provider "azuread" {}

# -----------------------------------------------------------------------------
# LOCALS
# Pulls names from naming.tf and builds common tags.
# -----------------------------------------------------------------------------
locals {
  names = local.naming_convention

  common_tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "Terraform"
    CostCenter  = var.cost_center
    Owner       = var.owner_email
    CreatedDate = formatdate("YYYY-MM-DD", timestamp())
  }

  # Convenience locals for conditional resource IDs passed between modules
  kv_id               = var.deploy_key_vault           ? module.key_vault[0].id              : var.existing_key_vault_id
  storage_id          = var.deploy_storage             ? module.storage[0].id               : var.existing_storage_id
  app_insights_id     = var.deploy_application_insights ? module.application_insights[0].id : var.existing_app_insights_id
  law_id              = var.deploy_log_analytics        ? module.log_analytics[0].workspace_id : null
  pe_subnet_id        = var.deploy_networking           ? module.networking[0].subnet_ids["private-endpoints"] : null
  foundry_mi_id       = var.deploy_managed_identity     ? module.managed_identity[0].foundry_identity_id : null
  foundry_mi_pid      = var.deploy_managed_identity     ? module.managed_identity[0].foundry_identity_principal_id : null
  apps_mi_id          = var.deploy_managed_identity     ? module.managed_identity[0].apps_identity_id : null
  apps_mi_pid         = var.deploy_managed_identity     ? module.managed_identity[0].apps_identity_principal_id : null
  apps_mi_client_id   = var.deploy_managed_identity     ? module.managed_identity[0].apps_identity_client_id : null
  build_mi_id         = var.deploy_managed_identity     ? module.managed_identity[0].build_identity_id : null
  build_mi_pid        = var.deploy_managed_identity     ? module.managed_identity[0].build_identity_principal_id : null
  openai_endpoint     = var.deploy_openai               ? module.openai[0].endpoint : ""
  openai_resource_id  = var.deploy_openai               ? module.openai[0].id : ""
  ai_search_endpoint  = var.deploy_ai_search            ? module.ai_search[0].endpoint : ""
  ai_search_id        = var.deploy_ai_search            ? module.ai_search[0].id : ""
  cosmos_endpoint     = var.deploy_cosmos_db            ? module.cosmos_db[0].endpoint : ""
  storage_endpoint    = var.deploy_storage              ? module.storage[0].primary_blob_endpoint : ""
  cae_id              = var.deploy_container_app_env    ? module.container_app_environment[0].id : ""
  app_config_endpoint = var.deploy_app_configuration    ? module.app_configuration[0].endpoint : ""
  apim_private_ips    = var.deploy_api_management       ? module.api_management[0].private_ip_addresses : []
}

###############################################################################
# FOUNDATION: RESOURCE GROUP
###############################################################################
module "resource_group" {
  source = "./modules/resource_group"

  name     = local.names.resource_group
  location = var.location
  tags     = local.common_tags
}

###############################################################################
# FOUNDATION: MANAGED IDENTITIES
# User-assigned identities provisioned early so downstream modules can
# pre-authorize them before the principal resources are created.
#
# Creates:
#   id-foundry-* — AI Foundry Hub, Project, Agent Service
#   id-apps-*    — Container App microservices (Dapr sidecar auth)
#   id-build-*   — Self-hosted CI/CD build agent VM
###############################################################################
module "managed_identity" {
  source = "./modules/managed_identity"

  count = var.deploy_managed_identity ? 1 : 0

  resource_group_name   = module.resource_group.name
  location              = var.location
  foundry_identity_name = local.names.managed_identity_foundry
  apps_identity_name    = local.names.managed_identity_apps
  build_identity_name   = local.names.managed_identity_build
  tags                  = local.common_tags

  depends_on = [module.resource_group]
}

###############################################################################
# FOUNDATION: SECURITY & GOVERNANCE
# Subscription-level controls enabled first so all resources inherit them.
#
# Covers the "Security & governance" band in the reference architecture:
#   - Subscription policy assignments
#   - Defender for Cloud (CSPM + Defender for AI)
#   - Microsoft Purview (data governance)
#   - Network Watcher
###############################################################################
module "security_governance" {
  source = "./modules/security_governance"

  count = var.deploy_security_governance ? 1 : 0

  resource_group_name       = module.resource_group.name
  location                  = var.location
  subscription_id           = var.spoke_subscription_id
  network_watcher_name      = local.names.network_watcher
  log_analytics_workspace_id = local.law_id
  security_contact_emails   = var.alert_email_addresses
  deploy_purview            = var.purview_account_name != "" ? true : false
  purview_account_name      = var.purview_account_name != "" ? var.purview_account_name : local.names.purview_account
  tags                      = local.common_tags

  depends_on = [module.resource_group, module.log_analytics]
}

###############################################################################
# FOUNDATION: AZURE POLICY
# Enforces compliance guardrails on all deployed resources:
#   - Allowed locations (canadacentral, canadaeast, eastus, eastus2)
#   - Deny public network access on AI services
#   - Required tags on all resources
#   - Require HTTPS on Storage
#   - Require purge protection on Key Vault
###############################################################################
module "policy" {
  source = "./modules/policy"

  count = var.deploy_policy ? 1 : 0

  resource_group_id         = module.resource_group.id
  resource_group_name       = module.resource_group.name
  location                  = var.location
  environment               = var.environment
  allowed_locations         = var.allowed_locations
  deny_public_access_effect = var.deny_public_access_effect
  tags                      = local.common_tags

  depends_on = [module.resource_group]
}

###############################################################################
# OBSERVABILITY: LOG ANALYTICS WORKSPACE
# Central log sink for all platform services, Defender, Entra ID, and apps.
# Deployed early — most modules depend on its workspace_id.
###############################################################################
module "log_analytics" {
  source = "./modules/log_analytics"

  count = var.deploy_log_analytics ? 1 : 0

  name                = local.names.log_analytics_workspace
  resource_group_name = module.resource_group.name
  location            = var.location
  sku                 = var.log_analytics_sku
  retention_days      = var.log_retention_days
  tags                = local.common_tags

  depends_on = [module.resource_group]
}

###############################################################################
# OBSERVABILITY: AZURE MONITOR
# Alert rules, action groups, and diagnostic settings.
###############################################################################
module "monitor" {
  source = "./modules/monitor"

  count = var.deploy_monitor ? 1 : 0

  resource_group_name        = module.resource_group.name
  location                   = var.location
  log_analytics_workspace_id = local.law_id
  alert_email_addresses      = var.alert_email_addresses
  project_name               = var.project_name
  environment                = var.environment
  tags                       = local.common_tags

  depends_on = [module.log_analytics]
}

###############################################################################
# OBSERVABILITY: APPLICATION INSIGHTS
# APM linked to Log Analytics. Used by AI Foundry Hub, AML, and Container Apps.
###############################################################################
module "application_insights" {
  source = "./modules/application_insights"

  count = var.deploy_application_insights ? 1 : 0

  name                       = local.names.application_insights
  resource_group_name        = module.resource_group.name
  location                   = var.location
  application_type           = "web"
  log_analytics_workspace_id = local.law_id
  tags                       = local.common_tags

  depends_on = [module.log_analytics]
}

###############################################################################
# NETWORKING: SPOKE VNET + SUBNETS
#
# Provisions all subnets matching the reference architecture:
#   private-endpoints      /27  — all service private endpoint NICs
#   ai-foundry-agent       /28  — AI Foundry Agent Service runtime
#   api-management         /29  — APIM internal VNet integration
#   container-app-env      /29  — Container App Environment
#   application-gateway    /28  — App Gateway (requires dedicated subnet)
#   build-agent            /29  — Self-hosted CI/CD build agent VM
#   jumpbox                /29  — Admin jump box VM
#   databricks-public      /28  — Reserved for future Databricks
#   databricks-private     /28  — Reserved for future Databricks
#
# NOTE: Hub VNET peering is NOT performed here.
#       Run scripts\setup-peering.ps1 after deployment.
###############################################################################
module "networking" {
  source = "./modules/networking"

  count = var.deploy_networking ? 1 : 0

  vnet_name           = local.names.virtual_network
  resource_group_name = module.resource_group.name
  location            = var.location
  vnet_address_space  = var.vnet_address_space
  subnets             = var.subnets
  tags                = local.common_tags

  depends_on = [module.resource_group]
}

###############################################################################
# NETWORKING: NETWORK SECURITY GROUPS
# Per-subnet NSG rules. Denies all internet inbound/outbound by default.
# Allows required Azure service tags and inter-subnet communication.
###############################################################################
module "nsg" {
  source = "./modules/nsg"

  count = var.deploy_networking ? 1 : 0

  resource_group_name = module.resource_group.name
  location            = var.location
  subnets             = var.subnets
  vnet_name           = local.names.virtual_network
  tags                = local.common_tags

  depends_on = [module.networking]
}

###############################################################################
# CORE SERVICE: KEY VAULT
# Shared secret store for AI Foundry, Container Apps, and build agents.
# All service connections, API keys, and SSL certificates stored here.
# RBAC auth model; purge protection enabled.
###############################################################################
module "key_vault" {
  source = "./modules/key_vault"

  count = var.deploy_key_vault ? 1 : 0

  name                       = local.names.key_vault
  resource_group_name        = module.resource_group.name
  location                   = var.location
  sku_name                   = var.key_vault_sku
  tenant_id                  = var.tenant_id
  log_analytics_workspace_id = local.law_id
  allowed_subnet_ids         = var.deploy_networking ? [
    module.networking[0].subnet_ids["private-endpoints"],
    module.networking[0].subnet_ids["ai-foundry-agent"],
    module.networking[0].subnet_ids["container-app-environment"]
  ] : []
  tags = local.common_tags

  depends_on = [module.networking, module.log_analytics]
}

###############################################################################
# CORE SERVICE: STORAGE ACCOUNT (FOUNDRY + APP ARTIFACTS)
# ADLS Gen2 (HNS enabled). Shared by AI Foundry Hub and GenAI app dependencies.
# Separate logical containers for foundry artifacts and app data.
###############################################################################
module "storage" {
  source = "./modules/storage"

  count = var.deploy_storage ? 1 : 0

  name                       = local.names.storage_account
  resource_group_name        = module.resource_group.name
  location                   = var.location
  account_tier               = var.storage_account_tier
  account_replication_type   = var.storage_replication_type
  is_hns_enabled             = true
  log_analytics_workspace_id = local.law_id
  allowed_subnet_ids         = var.deploy_networking ? [
    module.networking[0].subnet_ids["private-endpoints"],
    module.networking[0].subnet_ids["ai-foundry-agent"],
    module.networking[0].subnet_ids["container-app-environment"]
  ] : []
  tags = local.common_tags

  depends_on = [module.networking, module.log_analytics]
}

###############################################################################
# CORE SERVICE: CONTAINER REGISTRY
# Premium SKU with private endpoint. Stores container images for:
#   - GenAI microservices (frontend, orchestrator, sk, mcp, ingestion)
#   - AI Foundry Agent Service container
###############################################################################
module "container_registry" {
  source = "./modules/container_registry"

  count = var.deploy_container_registry ? 1 : 0

  name                       = local.names.container_registry
  resource_group_name        = module.resource_group.name
  location                   = var.location
  sku                        = var.container_registry_sku
  log_analytics_workspace_id = local.law_id
  allowed_subnet_ids         = var.deploy_networking ? [
    module.networking[0].subnet_ids["private-endpoints"],
    module.networking[0].subnet_ids["build-agent"]
  ] : []
  tags = local.common_tags

  depends_on = [module.networking, module.log_analytics]
}

###############################################################################
# AI SERVICE: COGNITIVE SERVICES (AI SERVICES ENDPOINTS)
# Multi-service account providing the "AI Services endpoints" shown in the
# AI Foundry Project. Used by AI Foundry connections and direct app calls.
###############################################################################
module "cognitive_services" {
  source = "./modules/cognitive_services"

  count = var.deploy_cognitive_services ? 1 : 0

  name                       = local.names.cognitive_services
  resource_group_name        = module.resource_group.name
  location                   = var.location
  sku_name                   = var.cognitive_services_sku
  log_analytics_workspace_id = local.law_id
  allowed_subnet_ids         = var.deploy_networking ? [
    module.networking[0].subnet_ids["private-endpoints"],
    module.networking[0].subnet_ids["ai-foundry-agent"]
  ] : []
  tags = local.common_tags

  depends_on = [module.networking, module.log_analytics]
}

###############################################################################
# AI SERVICE: AZURE OPENAI
# Provides "Foundry models" in the AI Foundry Project.
# Wired via Foundry connection to the hub workspace.
# Restricted regions: eastus, eastus2, canadaeast support OpenAI.
###############################################################################
module "openai" {
  source = "./modules/openai"

  count = var.deploy_openai ? 1 : 0

  name                       = local.names.openai_service
  resource_group_name        = module.resource_group.name
  location                   = var.openai_location
  sku_name                   = "S0"
  model_deployments          = var.openai_model_deployments
  log_analytics_workspace_id = local.law_id
  allowed_subnet_ids         = var.deploy_networking ? [
    module.networking[0].subnet_ids["private-endpoints"],
    module.networking[0].subnet_ids["ai-foundry-agent"]
  ] : []
  tags = local.common_tags

  depends_on = [module.networking, module.log_analytics]
}

###############################################################################
# AI FOUNDRY DEPENDENCY: AZURE AI SEARCH
# Vector index for RAG grounding used by:
#   - AI Foundry Agent Service (Connections -> AI Search)
#   - GenAI app Ingestion pipeline (indexing documents)
#   - GenAI app Orchestrator (retrieval during inference)
# Also serves as the "AI Search Service" in Enterprise knowledge sources.
###############################################################################
module "ai_search" {
  source = "./modules/ai_search"

  count = var.deploy_ai_search ? 1 : 0

  name                       = local.names.ai_search
  resource_group_name        = module.resource_group.name
  location                   = var.location
  sku                        = var.ai_search_sku
  replica_count              = var.ai_search_replica_count
  partition_count            = var.ai_search_partition_count
  log_analytics_workspace_id = local.law_id
  pe_name                    = local.names.pe_ai_search
  pe_subnet_id               = local.pe_subnet_id
  tags                       = local.common_tags

  depends_on = [module.networking, module.log_analytics]
}

###############################################################################
# AI FOUNDRY DEPENDENCY: COSMOS DB
# NoSQL document store used as:
#   - AI Foundry Agent Service memory (sessions, history, entities)
#   - GenAI app state and result caching (app-data database)
###############################################################################
module "cosmos_db" {
  source = "./modules/cosmos_db"

  count = var.deploy_cosmos_db ? 1 : 0

  name                       = local.names.cosmos_db_account
  resource_group_name        = module.resource_group.name
  location                   = var.location
  offer_type                 = var.cosmos_db_offer_type
  kind                       = var.cosmos_db_kind
  consistency_level          = var.cosmos_db_consistency_level
  databases                  = var.cosmos_db_databases
  log_analytics_workspace_id = local.law_id
  pe_name                    = local.names.pe_cosmos_db
  pe_subnet_id               = local.pe_subnet_id
  tags                       = local.common_tags

  depends_on = [module.networking, module.log_analytics]
}

###############################################################################
# AZURE MACHINE LEARNING
# Optional classic AML workspace for data science workloads alongside
# AI Foundry. Kept separate from the Foundry hub.
###############################################################################
module "machine_learning" {
  source = "./modules/machine_learning"

  count = var.deploy_machine_learning ? 1 : 0

  name                       = local.names.machine_learning_workspace
  resource_group_name        = module.resource_group.name
  location                   = var.location
  sku_name                   = var.machine_learning_sku
  key_vault_id               = local.kv_id
  storage_account_id         = local.storage_id
  application_insights_id    = local.app_insights_id
  container_registry_id      = var.deploy_container_registry ? module.container_registry[0].id : null
  log_analytics_workspace_id = local.law_id
  allowed_subnet_ids         = var.deploy_networking ? [module.networking[0].subnet_ids["private-endpoints"]] : []
  tags                       = local.common_tags

  depends_on = [
    module.key_vault, module.storage, module.application_insights,
    module.container_registry, module.networking, module.log_analytics
  ]
}

###############################################################################
# AI FOUNDRY: COMPLETE SERVICE SETUP
#
# Deploys the full "AI Foundry Agent Service standard setup":
#   AI Foundry Hub         (azurerm_machine_learning_workspace kind=Hub)
#   AI Foundry Project     (child project with model/connection/agent scope)
#   AI Foundry Connections (to OpenAI, AI Search, Cosmos DB)
#   AI Foundry Agent Service (Container App in ai-foundry-agent subnet)
#   Private Endpoint       (AI Foundry Hub in private-endpoints subnet)
#   Managed identity RBAC  (Foundry MI -> Storage, Search, KV, OpenAI)
#
# Dependencies:
#   Storage, Key Vault, App Insights, AI Search, Cosmos DB, OpenAI (optional)
###############################################################################
module "ai_foundry" {
  source = "./modules/ai_foundry"

  count = var.deploy_ai_foundry ? 1 : 0

  resource_group_name          = module.resource_group.name
  location                     = var.location
  hub_name                     = local.names.ai_foundry_hub
  project_name                 = local.names.ai_foundry_project
  managed_identity_name        = local.names.managed_identity_foundry
  agent_service_name           = local.names.ai_foundry_agent_service
  sku                          = var.ai_foundry_sku
  storage_account_id           = local.storage_id
  key_vault_id                 = local.kv_id
  application_insights_id      = local.app_insights_id
  log_analytics_workspace_id   = local.law_id
  pe_name                      = local.names.pe_ai_foundry
  pe_subnet_id                 = local.pe_subnet_id
  container_app_environment_id = local.cae_id
  openai_endpoint              = local.openai_endpoint
  openai_resource_id           = local.openai_resource_id
  ai_search_endpoint           = local.ai_search_endpoint
  ai_search_id                 = local.ai_search_id
  cosmos_db_endpoint           = local.cosmos_endpoint
  tags                         = local.common_tags

  depends_on = [
    module.storage, module.key_vault, module.application_insights,
    module.ai_search, module.cosmos_db, module.openai,
    module.container_app_environment, module.log_analytics, module.networking
  ]
}

###############################################################################
# GENAI APP: APP CONFIGURATION
# Centralised feature flags and settings for all GenAI microservices.
# Container Apps read configuration at startup via managed identity.
###############################################################################
module "app_configuration" {
  source = "./modules/app_configuration"

  count = var.deploy_app_configuration ? 1 : 0

  name                         = local.names.app_configuration
  resource_group_name          = module.resource_group.name
  location                     = var.location
  pe_name                      = local.names.pe_app_configuration
  pe_subnet_id                 = local.pe_subnet_id
  log_analytics_workspace_id   = local.law_id
  apps_identity_principal_id   = local.apps_mi_pid != null ? local.apps_mi_pid : ""
  tags                         = local.common_tags

  depends_on = [module.networking, module.log_analytics, module.managed_identity]
}

###############################################################################
# GENAI APP: CONTAINER APP ENVIRONMENT + MICROSERVICES
#
# The Container App Environment hosts all GenAI application microservices:
#   Frontend     — user-facing API / UI, exposed via App Gateway
#   Orchestrator — core agent loop (Semantic Kernel / LangChain)
#   SK           — Semantic Kernel plugin host
#   MCP          — Model Context Protocol server (tool/resource exposure)
#   Ingestion    — RAG data ingestion pipeline (chunk -> embed -> index)
#
# All microservices are Dapr-enabled for service-to-service invocation,
# pub/sub messaging, state store (Cosmos DB), and secret access (Key Vault).
###############################################################################
module "container_app_environment" {
  source = "./modules/container_app_environment"

  count = var.deploy_container_app_env ? 1 : 0

  name                         = local.names.container_app_environment
  resource_group_name          = module.resource_group.name
  location                     = var.location
  subnet_id                    = var.deploy_networking ? module.networking[0].subnet_ids["container-app-environment"] : null
  pe_subnet_id                 = local.pe_subnet_id
  pe_name                      = local.names.pe_container_app_env
  log_analytics_workspace_id   = local.law_id
  apps_identity_id             = local.apps_mi_id != null ? local.apps_mi_id : ""
  apps_identity_client_id      = local.apps_mi_client_id != null ? local.apps_mi_client_id : ""
  frontend_app_name            = local.names.container_app_frontend
  orchestrator_app_name        = local.names.container_app_orchestrator
  sk_app_name                  = local.names.container_app_sk
  mcp_app_name                 = local.names.container_app_mcp
  ingestion_app_name           = local.names.container_app_ingestion
  openai_endpoint              = local.openai_endpoint
  ai_search_endpoint           = local.ai_search_endpoint
  cosmos_db_endpoint           = local.cosmos_endpoint
  storage_endpoint             = local.storage_endpoint
  app_insights_connection_string = var.deploy_application_insights ? module.application_insights[0].connection_string : ""
  app_configuration_endpoint   = local.app_config_endpoint
  tags                         = local.common_tags

  depends_on = [
    module.networking, module.log_analytics, module.managed_identity,
    module.openai, module.ai_search, module.cosmos_db, module.storage,
    module.app_configuration
  ]
}

###############################################################################
# INGRESS: API MANAGEMENT (APIM)
# Internal VNet mode — sits between App Gateway and Container Apps.
# Provides rate limiting, JWT validation, and backend routing for all
# GenAI API endpoints exposed to consumers.
###############################################################################
module "api_management" {
  source = "./modules/api_management"

  count = var.deploy_api_management ? 1 : 0

  name                       = local.names.api_management
  resource_group_name        = module.resource_group.name
  location                   = var.location
  sku_name                   = "${var.apim_sku}_1"
  publisher_name             = var.apim_publisher_name
  publisher_email            = var.apim_publisher_email
  subnet_id                  = var.deploy_networking ? module.networking[0].subnet_ids["api-management"] : null
  pe_subnet_id               = local.pe_subnet_id
  pe_name                    = local.names.pe_apim
  log_analytics_workspace_id = local.law_id
  tags                       = local.common_tags

  depends_on = [module.networking, module.log_analytics]
}

###############################################################################
# INGRESS: APPLICATION GATEWAY + WAF
# Public-facing HTTPS ingress layer. WAF v2 in Prevention mode with OWASP 3.2.
# Backend pool = APIM internal gateway IP.
# Traffic flow: Internet -> WAF -> APIM -> Container Apps
###############################################################################
module "app_gateway" {
  source = "./modules/app_gateway"

  count = var.deploy_app_gateway ? 1 : 0

  name                       = local.names.app_gateway
  resource_group_name        = module.resource_group.name
  location                   = var.location
  public_ip_name             = local.names.app_gateway_public_ip
  waf_policy_name            = local.names.app_gateway_waf_policy
  subnet_id                  = var.deploy_networking ? module.networking[0].subnet_ids["application-gateway"] : null
  log_analytics_workspace_id = local.law_id
  apim_private_ip_addresses  = local.apim_private_ips
  gateway_identity_id        = local.apps_mi_id != null ? local.apps_mi_id : ""
  tags                       = local.common_tags

  depends_on = [module.networking, module.log_analytics, module.api_management, module.managed_identity]
}

###############################################################################
# ADMIN: JUMP BOX VM
# Linux VM in the jumpbox subnet for secure administrative access.
# No public IP — accessed via Azure Bastion (hub) or VPN.
# Entra ID login extension enables passwordless SSH.
###############################################################################
module "jumpbox" {
  source = "./modules/jumpbox"

  count = var.deploy_jumpbox ? 1 : 0

  name                = local.names.jumpbox_vm
  nic_name            = local.names.jumpbox_nic
  resource_group_name = module.resource_group.name
  location            = var.location
  subnet_id           = var.deploy_networking ? module.networking[0].subnet_ids["jumpbox"] : null
  vm_size             = var.jumpbox_vm_size
  admin_username      = var.jumpbox_admin_username
  admin_ssh_public_key = var.admin_ssh_public_key
  tags                = local.common_tags

  depends_on = [module.networking]
}

###############################################################################
# ADMIN: BUILD AGENT VM
# Self-hosted CI/CD agent in the build-agent subnet.
# Managed identity pre-authorized to push to ACR and deploy to Container Apps.
###############################################################################
module "build_agent" {
  source = "./modules/build_agent"

  count = var.deploy_build_agent ? 1 : 0

  name                         = local.names.build_agent_vm
  nic_name                     = local.names.build_agent_nic
  resource_group_name          = module.resource_group.name
  location                     = var.location
  subnet_id                    = var.deploy_networking ? module.networking[0].subnet_ids["build-agent"] : null
  build_identity_id            = local.build_mi_id != null ? local.build_mi_id : ""
  build_identity_principal_id  = local.build_mi_pid != null ? local.build_mi_pid : ""
  vm_size                      = var.build_agent_vm_size
  admin_username               = var.build_agent_admin_username
  admin_ssh_public_key         = var.admin_ssh_public_key
  container_registry_id        = var.deploy_container_registry ? module.container_registry[0].id : ""
  container_app_environment_id = local.cae_id
  tags                         = local.common_tags

  depends_on = [module.networking, module.managed_identity, module.container_registry, module.container_app_environment]
}

###############################################################################
# PRIVATE ENDPOINTS: ALL SERVICES
# Consolidates private endpoint creation for all platform services.
# All endpoints land in the private-endpoints subnet.
# DNS A records must be registered in hub-hosted private DNS zones.
#
# Services covered (13 endpoints across all deployed services):
#   Core:         Key Vault, Storage (blob+dfs), Container Registry
#   AI/ML:        AML Workspace, Cognitive Services, OpenAI, AI Foundry Hub
#   Foundry deps: AI Search, Cosmos DB
#   App:          App Configuration, APIM
#   Observability: Log Analytics
###############################################################################
module "private_endpoints" {
  source = "./modules/private_endpoints"

  count = var.deploy_private_endpoints && var.deploy_networking ? 1 : 0

  resource_group_name   = module.resource_group.name
  location              = var.location
  subnet_id             = local.pe_subnet_id
  hub_vnet_id           = var.hub_vnet_id

  # ── Core services ────────────────────────────────────────────────────────
  key_vault_id          = var.deploy_key_vault          ? module.key_vault[0].id          : null
  storage_account_id    = var.deploy_storage            ? module.storage[0].id            : null
  container_registry_id = var.deploy_container_registry ? module.container_registry[0].id : null

  # ── AI / ML services ────────────────────────────────────────────────────
  machine_learning_id   = var.deploy_machine_learning   ? module.machine_learning[0].id   : null
  cognitive_services_id = var.deploy_cognitive_services ? module.cognitive_services[0].id : null
  openai_id             = var.deploy_openai             ? module.openai[0].id             : null
  ai_foundry_id         = var.deploy_ai_foundry         ? module.ai_foundry[0].hub_id     : null

  # ── AI Foundry dependencies ───────────────────────────────────────────────
  ai_search_id          = var.deploy_ai_search          ? module.ai_search[0].id          : null
  cosmos_db_id          = var.deploy_cosmos_db          ? module.cosmos_db[0].id          : null

  # ── GenAI app dependencies ───────────────────────────────────────────────
  app_configuration_id  = var.deploy_app_configuration  ? module.app_configuration[0].id  : null

  # ── Ingress and observability ────────────────────────────────────────────
  log_analytics_id      = var.deploy_log_analytics      ? module.log_analytics[0].workspace_id : null
  api_management_id     = var.deploy_api_management     ? module.api_management[0].id      : null

  tags = local.common_tags

  depends_on = [
    module.networking, module.key_vault, module.storage,
    module.container_registry, module.machine_learning,
    module.cognitive_services, module.openai, module.log_analytics,
    module.ai_foundry, module.ai_search, module.cosmos_db,
    module.app_configuration, module.api_management
  ]
}

###############################################################################
# RBAC: ROLE ASSIGNMENTS
# Assigns Azure RBAC roles to AAD groups and managed identities.
# See docs/roles.md for the complete role assignment matrix.
###############################################################################
module "rbac" {
  source = "./modules/rbac"

  count = var.deploy_rbac ? 1 : 0

  resource_group_id          = module.resource_group.id
  machine_learning_id        = var.deploy_machine_learning ? module.machine_learning[0].id : null
  storage_account_id         = local.storage_id
  key_vault_id               = local.kv_id
  openai_id                  = var.deploy_openai ? module.openai[0].id : null
  data_scientist_group_id    = var.data_scientist_group_id
  ml_engineer_group_id       = var.ml_engineer_group_id
  data_engineer_group_id     = var.data_engineer_group_id
  ai_app_developer_group_id  = var.ai_app_developer_group_id
  platform_admin_group_id    = var.platform_admin_group_id

  depends_on = [
    module.machine_learning, module.storage, module.key_vault, module.openai
  ]
}
