#!/usr/bin/env bash
###############################################################################
# scripts/bootstrap.sh
# PURPOSE: Pre-deployment bootstrap script.
#          Creates the Terraform state storage account and container BEFORE
#          running terraform init. This must run once per environment.
#
# PREREQUISITES:
#   - Azure CLI installed and authenticated (az login)
#   - Contributor access to the target subscription
#   - Environment variables set (or passed as arguments)
#
# USAGE:
#   export SUBSCRIPTION_ID="<your-subscription-id>"
#   export ENVIRONMENT="prod"
#   export LOCATION="canadacentral"
#   ./scripts/bootstrap.sh
###############################################################################

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────
SUBSCRIPTION_ID="${SUBSCRIPTION_ID:?'SUBSCRIPTION_ID environment variable is required'}"
ENVIRONMENT="${ENVIRONMENT:-prod}"
LOCATION="${LOCATION:-canadacentral}"

# Derive location short code for naming
case "$LOCATION" in
  "canadacentral") LOCATION_SHORT="cc" ;;
  "canadaeast")    LOCATION_SHORT="ce" ;;
  "eastus")        LOCATION_SHORT="eu" ;;
  "eastus2")       LOCATION_SHORT="eu2" ;;
  *)               LOCATION_SHORT="${LOCATION:0:4}" ;;
esac

# Terraform state resource names (must match backend.hcl)
TF_STATE_RG="rg-tfstate-${ENVIRONMENT}-${LOCATION_SHORT}"
TF_STATE_SA="sttfstate${ENVIRONMENT}${LOCATION_SHORT}"
TF_STATE_CONTAINER="tfstate"

echo "============================================================"
echo "Azure AI Landing Zone - Terraform State Bootstrap"
echo "============================================================"
echo "Subscription:   ${SUBSCRIPTION_ID}"
echo "Environment:    ${ENVIRONMENT}"
echo "Location:       ${LOCATION}"
echo "Resource Group: ${TF_STATE_RG}"
echo "Storage Account:${TF_STATE_SA}"
echo "============================================================"

# ─────────────────────────────────────────────────────────────────────────────
# SET SUBSCRIPTION CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
echo "[1/5] Setting Azure subscription context..."
az account set --subscription "${SUBSCRIPTION_ID}"
echo "      Active subscription: $(az account show --query name -o tsv)"

# ─────────────────────────────────────────────────────────────────────────────
# CREATE RESOURCE GROUP FOR TERRAFORM STATE
# ─────────────────────────────────────────────────────────────────────────────
echo "[2/5] Creating Terraform state resource group: ${TF_STATE_RG}"
az group create \
  --name "${TF_STATE_RG}" \
  --location "${LOCATION}" \
  --tags "ManagedBy=Bootstrap" "Environment=${ENVIRONMENT}" "Purpose=TerraformState" \
  --output table

# ─────────────────────────────────────────────────────────────────────────────
# CREATE STORAGE ACCOUNT FOR TERRAFORM STATE
# GRS replication for geo-redundancy; minimum TLS 1.2; HTTPS only
# ─────────────────────────────────────────────────────────────────────────────
echo "[3/5] Creating Terraform state storage account: ${TF_STATE_SA}"
az storage account create \
  --name "${TF_STATE_SA}" \
  --resource-group "${TF_STATE_RG}" \
  --location "${LOCATION}" \
  --sku "Standard_GRS" \
  --kind "StorageV2" \
  --access-tier "Hot" \
  --https-only true \
  --min-tls-version "TLS1_2" \
  --allow-blob-public-access false \
  --tags "ManagedBy=Bootstrap" "Environment=${ENVIRONMENT}" "Purpose=TerraformState" \
  --output table

# ─────────────────────────────────────────────────────────────────────────────
# ENABLE BLOB VERSIONING (protect state file history)
# ─────────────────────────────────────────────────────────────────────────────
echo "[4/5] Enabling blob versioning on state storage account..."
az storage account blob-service-properties update \
  --account-name "${TF_STATE_SA}" \
  --resource-group "${TF_STATE_RG}" \
  --enable-versioning true \
  --enable-delete-retention true \
  --delete-retention-days 30

# ─────────────────────────────────────────────────────────────────────────────
# CREATE TERRAFORM STATE CONTAINER
# ─────────────────────────────────────────────────────────────────────────────
echo "[5/5] Creating Terraform state container: ${TF_STATE_CONTAINER}"
az storage container create \
  --name "${TF_STATE_CONTAINER}" \
  --account-name "${TF_STATE_SA}" \
  --auth-mode login \
  --output table

# ─────────────────────────────────────────────────────────────────────────────
# GENERATE BACKEND.HCL
# ─────────────────────────────────────────────────────────────────────────────
cat > backend.hcl << EOF
# Generated by scripts/bootstrap.sh - DO NOT COMMIT THIS FILE
resource_group_name  = "${TF_STATE_RG}"
storage_account_name = "${TF_STATE_SA}"
container_name       = "${TF_STATE_CONTAINER}"
key                  = "ai-landing-zone.tfstate"
EOF

echo ""
echo "============================================================"
echo "Bootstrap COMPLETE!"
echo "============================================================"
echo ""
echo "backend.hcl has been generated. Next steps:"
echo ""
echo "  1. Copy the example variable file to terraform.tfvars:"
echo "     Windows:  copy terraform.tfvars.example terraform.tfvars"
echo "     Linux:    cp  terraform.tfvars.example  terraform.tfvars"
echo "     Then update with your subscription ID, tenant ID, and settings."
echo ""
echo "  2. Initialize Terraform with remote state:"
echo "     terraform init -backend-config=\"backend.hcl\""
echo ""
echo "  3. Review the deployment plan:"
echo "     terraform plan -var-file=\"terraform.tfvars\""
echo ""
echo "  4. Deploy:"
echo "     terraform apply -var-file=\"terraform.tfvars\""
echo ""
echo "  See README.md for full deployment documentation."
echo "============================================================"
